-- Gamerhood initial schema
-- Parent-owned accounts with child profiles (COPPA compliant)

-- Parents table: the adult account holder
create table public.parents (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique not null references auth.users(id) on delete cascade,
  email text not null,
  display_name text not null,
  stripe_connect_id text,
  stripe_onboarding_complete boolean default false,
  consent_method text check (consent_method in ('credit_card', 'esign', 'id_verify')),
  consent_verified_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Child profiles / storefronts (no PII — display name and avatar only)
create table public.profiles (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid not null references public.parents(id) on delete cascade,
  display_name text not null,
  slug text unique not null,
  avatar_url text,
  bio text default '',
  level int default 1,
  xp int default 0,
  is_active boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index idx_profiles_slug on public.profiles(slug);
create index idx_profiles_parent on public.profiles(parent_id);

-- Designs uploaded or AI-generated by creators
create table public.designs (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  image_url text not null,
  prompt text,
  style text not null check (style in (
    'anime', 'streetwear', 'pixel-art', 'graffiti',
    'minimalist', 'vaporwave', 'comic', 'realistic'
  )),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  moderation_notes text,
  content_safe boolean,
  copyright_clear boolean,
  created_at timestamptz default now()
);

create index idx_designs_profile on public.designs(profile_id);
create index idx_designs_status on public.designs(status);

-- Products: a design applied to a specific merch type via Printify
create table public.products (
  id uuid primary key default gen_random_uuid(),
  design_id uuid not null references public.designs(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  printify_product_id text,
  title text not null,
  description text default '',
  product_type text not null check (product_type in (
    'hoodie', 'tshirt', 'joggers', 'mug', 'poster',
    'backpack', 'phone-case', 'sticker'
  )),
  base_price_cents int not null,
  markup_cents int not null,
  mockup_url text,
  colors text[] default '{}',
  sizes text[] default '{}',
  is_published boolean default false,
  sales_count int default 0,
  created_at timestamptz default now()
);

create index idx_products_profile on public.products(profile_id);
create index idx_products_published on public.products(is_published) where is_published = true;

-- Orders
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  buyer_email text not null,
  stripe_payment_id text,
  printify_order_id text,
  status text not null default 'pending' check (status in (
    'pending', 'processing', 'shipped', 'delivered', 'cancelled'
  )),
  total_cents int not null,
  platform_fee_cents int not null,
  shipping_address jsonb,
  tracking_number text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Order line items
create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid not null references public.products(id),
  profile_id uuid not null references public.profiles(id),
  quantity int not null default 1,
  unit_price_cents int not null,
  creator_earnings_cents int not null,
  selected_color text,
  selected_size text
);

create index idx_order_items_order on public.order_items(order_id);
create index idx_order_items_profile on public.order_items(profile_id);

-- Badges / achievements
create table public.badges (
  id text primary key,
  name text not null,
  icon text not null,
  description text not null,
  xp_reward int default 0
);

create table public.profile_badges (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  badge_id text not null references public.badges(id),
  earned_at timestamptz default now(),
  primary key (profile_id, badge_id)
);

-- DMCA tracking
create table public.dmca_reports (
  id uuid primary key default gen_random_uuid(),
  design_id uuid not null references public.designs(id),
  reporter_email text not null,
  reporter_name text not null,
  description text not null,
  status text not null default 'pending' check (status in ('pending', 'reviewed', 'upheld', 'rejected')),
  created_at timestamptz default now(),
  resolved_at timestamptz
);

create table public.copyright_strikes (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  dmca_report_id uuid references public.dmca_reports(id),
  reason text not null,
  created_at timestamptz default now()
);

-- RLS policies
alter table public.parents enable row level security;
alter table public.profiles enable row level security;
alter table public.designs enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Parents can only see/edit their own record
create policy "parents_own" on public.parents
  for all using (auth_user_id = auth.uid());

-- Parents can manage their children's profiles
create policy "profiles_parent_manage" on public.profiles
  for all using (
    parent_id in (select id from public.parents where auth_user_id = auth.uid())
  );

-- Anyone can view active profiles (public storefronts)
create policy "profiles_public_read" on public.profiles
  for select using (is_active = true);

-- Parents manage designs through their child profiles
create policy "designs_parent_manage" on public.designs
  for all using (
    profile_id in (
      select p.id from public.profiles p
      join public.parents pa on pa.id = p.parent_id
      where pa.auth_user_id = auth.uid()
    )
  );

-- Anyone can view approved designs
create policy "designs_public_read" on public.designs
  for select using (status = 'approved');

-- Parents manage products through their child profiles
create policy "products_parent_manage" on public.products
  for all using (
    profile_id in (
      select p.id from public.profiles p
      join public.parents pa on pa.id = p.parent_id
      where pa.auth_user_id = auth.uid()
    )
  );

-- Anyone can view published products
create policy "products_public_read" on public.products
  for select using (is_published = true);

-- Seed badges
insert into public.badges (id, name, icon, description, xp_reward) values
  ('first-design', 'First Drop', '🎨', 'Published your first design', 100),
  ('first-sale', 'Cha-Ching!', '💰', 'Made your first sale', 200),
  ('ten-sales', 'On Fire', '🔥', '10 sales and counting', 500),
  ('hundred-sales', 'Legend', '⚡', '100 sales — legendary status', 2000),
  ('five-designs', 'Creative Machine', '🎯', '5 designs published', 300),
  ('trending', 'Trending', '📈', 'Made it to trending', 500);
