import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import { GenerateDesignRequest } from "@/lib/types";
import { moderateText, moderateImageBase64 } from "@/lib/moderation";
import { createClient } from "@/lib/supabase/server";
import { getDefaultProfileForAuthUser, insertDesign } from "@/lib/supabase/queries";

const STYLE_MODIFIERS: Record<string, string> = {
  anime: "anime art style, cel shaded, vibrant colors, manga inspired",
  streetwear: "urban streetwear graphic design, bold typography, edgy",
  "pixel-art": "pixel art, 16-bit retro game style, crisp pixels",
  graffiti: "graffiti street art style, spray paint, dripping paint, bold",
  minimalist: "clean minimalist design, simple lines, modern, flat",
  vaporwave: "vaporwave aesthetic, pastel neons, retro 80s, glitch art",
  comic: "comic book style, halftone dots, bold outlines, pop art",
  realistic: "photorealistic digital art, highly detailed, dramatic lighting",
};

export async function POST(request: NextRequest) {
  let body: GenerateDesignRequest;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  if (!body.prompt?.trim()) {
    return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
  }

  const textCheck = await moderateText(body.prompt);
  if (!textCheck.safe) {
    return NextResponse.json(
      { error: "Your prompt contains content that isn't allowed. Please try a different description." },
      { status: 400 },
    );
  }

  const apiKey = process.env.GEMINI_API_KEY;

  /**
   * Dev/preview fallback: when Gemini isn't configured we serve a clearly
   * labelled placeholder so the rest of the flow (preview, publish, dashboard)
   * stays exercisable end-to-end. The placeholder image and the
   * `placeholder: true` flag both make it impossible to confuse this with a
   * real AI-generated design.
   */
  if (!apiKey) {
    const label = encodeURIComponent("DEMO MODE\nGEMINI_API_KEY\nnot set");
    const imageUrl = `https://placehold.co/1024x1024/1a1a2e/ff8906?text=${label}`;
    return NextResponse.json({
      imageUrl,
      prompt: body.prompt,
      style: body.style,
      placeholder: true,
      placeholderReason:
        "GEMINI_API_KEY is not set in .env.local — add your Google AI Studio key and restart the dev server to enable real AI image generation.",
    });
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const styleHint = STYLE_MODIFIERS[body.style] || "";
    const fullPrompt = `${body.prompt.trim()}, ${styleHint}, suitable for printing on merchandise, high quality, centered composition, no text or watermarks, square 1:1 aspect ratio`;

    const response = await ai.models.generateContent({
      model: "gemini-3.1-flash-image-preview",
      contents: fullPrompt,
      config: {
        responseModalities: ["TEXT", "IMAGE"],
      },
    });

    const parts = response.candidates?.[0]?.content?.parts;
    if (!parts) {
      throw new Error("No response from Gemini");
    }

    for (const part of parts) {
      if (!part.inlineData) continue;

      const mimeType = part.inlineData.mimeType || "image/png";
      const base64 = part.inlineData.data ?? "";
      const imageUrl = `data:${mimeType};base64,${base64}`;

      // Run Vision SafeSearch on the generated bytes. Fails closed when the
      // API errors so we don't leak unmoderated AI output to a kid-facing UI.
      const imageCheck = await moderateImageBase64(base64);
      if (!imageCheck.safe) {
        console.warn("[Design Generate] Image flagged:", imageCheck.flags);
        return NextResponse.json(
          {
            error:
              "The generated image was flagged by our safety check. Please try a different description.",
          },
          { status: 400 },
        );
      }

      let designId: string | null = null;
      try {
        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (user) {
          const { data: profile } = await getDefaultProfileForAuthUser(supabase, user.id);
          if (profile) {
            const { data: design } = await insertDesign(supabase, {
              profile_id: profile.id,
              title: body.prompt.slice(0, 80),
              image_url: imageUrl,
              prompt: body.prompt,
              style: body.style,
              // Both text and image moderation passed, so the design is
              // safe to surface in catalogs (RLS policy `designs_public_read`
              // requires status = 'approved').
              status: "approved",
              content_safe: true,
            });
            designId = design?.id ?? null;
          }
        }
      } catch (err) {
        console.error("[Design Generate] Save error:", err);
      }

      return NextResponse.json({
        imageUrl,
        prompt: body.prompt,
        style: body.style,
        designId,
      });
    }

    throw new Error("No image in Gemini response");
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);

    if (message.includes("SAFETY") || message.includes("blocked")) {
      return NextResponse.json(
        { error: "Your prompt was flagged by our safety system. Please try a different description." },
        { status: 400 },
      );
    }

    console.error("[Design Generate] Gemini error:", err);
    return NextResponse.json(
      { error: "Failed to generate design. Please try again." },
      { status: 500 },
    );
  }
}
